In [4]:
import pandas as pd
import os

In [5]:
print("--- LOADING PROCESSED DATA ---")

load_path = "./processed_videos/dataframe_videos_final.csv"
videos = pd.read_csv(load_path)

print(f"{len(videos)} videos loaded!")
pd.set_option('display.max_colwidth', None)
display(videos.sample(5))

load_path = "./processed_images/dataframe_images_final.csv"
full_fei_processed_df = pd.read_csv(load_path)

print(f"{len(full_fei_processed_df)} images loaded!")
pd.set_option('display.max_colwidth', None)
display(full_fei_processed_df.sample(5))

--- LOADING PROCESSED DATA ---
7000 videos loaded!

,video,label,method,target,source,sequence,exp_id,path,total_frames,fps,duration_sec,resolution,split_target_based,split_source_based
1855,672_720.mp4,1,Deepfakes,classic_672,classic_720,NaN,NaN,/Users/luciapola/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/FaceForensics++_C23/Deepfakes/672_720.mp4,541,30.0,18.033333,1280x720,train,train
647,18_11__walking_outside_cafe_disgusted__TRJUIS24.mp4,1,DeepFakeDetection,dfd_18,dfd_11,walking_outside_cafe_disgusted,TRJUIS24,/Users/luciapola/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/FaceForensics++_C23/DeepFakeDetection/18_11__walking_outside_cafe_disgusted__TRJUIS24.mp4,372,24.0,15.500000,1920x1080,train,test
1792,913_893.mp4,1,Deepfakes,classic_913,classic_893,NaN,NaN,/Users/luciapola/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/FaceForensics++_C23/Deepfakes/913_893.mp4,634,30.0,21.133333,632x480,train,train
3722,920_811.mp4,1,FaceShifter,classic_920,classic_811,NaN,NaN,/Users/luciapola/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/FaceForensics++_C23/FaceShifter/920_811.mp4,371,25.0,14.840000,1920x1080,train,train
1512,996_056.mp4,1,Deepfakes,classic_996,classic_056,NaN,NaN,/Users/luciapola/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/FaceForensics++_C23/Deepfakes/996_056.mp4,312,25.0,12.480000,720x480,train,train

8054 images loaded!

,filename,path,label,subj1,subj2,pose_number,pose_number_2,algorithm,morph_factor_1,morph_factor_2,post_proc_auto,post_proc_manual,digital_ps,resolution,detection_type,split
1523,M_28-11_197-11_C08_B50_W50_PA08_PM00_F00_ssd.png,/Users/luciapola/Desktop/internship-deepfake-forensic/deepfake-forensics-pipeline/FEI_Split/train/fake/M_28-11_197-11_C08_B50_W50_PA08_PM00_F00_ssd.png,1,28,197.0,11,11.0,C08,B50,W50,PA08,PM00,F00,224x224,ssd,train
4300,M_39-11_123-11_C03_B50_W50_PA03_PM00_F00_ssd.png,/Users/luciapola/Desktop/internship-deepfake-forensic/deepfake-forensics-pipeline/FEI_Split/train/fake/M_39-11_123-11_C03_B50_W50_PA03_PM00_F00_ssd.png,1,39,123.0,11,11.0,C03,B50,W50,PA03,PM00,F00,224x224,ssd,train
6146,M_106-11_84-11_C15_B30_W30_PA15_PM00_F00_ssd.png,/Users/luciapola/Desktop/internship-deepfake-forensic/deepfake-forensics-pipeline/FEI_Split/train/fake/M_106-11_84-11_C15_B30_W30_PA15_PM00_F00_ssd.png,1,106,84.0,11,11.0,C15,B30,W30,PA15,PM00,F00,224x224,ssd,train
1486,M_66-11_52-11_C05_B30_W30_PA05_PM00_F00_ssd.png,/Users/luciapola/Desktop/internship-deepfake-forensic/deepfake-forensics-pipeline/FEI_Split/train/fake/M_66-11_52-11_C05_B30_W30_PA05_PM00_F00_ssd.png,1,66,52.0,11,11.0,C05,B30,W30,PA05,PM00,F00,224x224,ssd,train
5899,M_79-11_132-11_C01_B50_W50_PA01_PM00_F00_ssd.png,/Users/luciapola/Desktop/internship-deepfake-forensic/deepfake-forensics-pipeline/FEI_Split/train/fake/M_79-11_132-11_C01_B50_W50_PA01_PM00_F00_ssd.png,1,79,132.0,11,11.0,C01,B50,W50,PA01,PM00,F00,224x224,ssd,train

In [6]:
df_fei = full_fei_processed_df[['path', 'label', 'split']].copy()
df_fei['dataset'] = 'FEI'

df_fei['label'] = df_fei['label'].replace({'original': 0, 'fake': 1}).astype(int) 

df_ff = videos[['path', 'label', 'split_target_based']].copy()
df_ff = df_ff.rename(columns={'split_target_based': 'split'})
df_ff['dataset'] = 'FF++'
df_ff['label'] = df_ff['label'].astype(int)

master_df = pd.concat([df_fei, df_ff], ignore_index=True)

master_df = master_df.sample(frac=1, random_state=42).reset_index(drop=True)

master_df.to_csv("master_dataset.csv", index=False)
print("Merge completed! File saved as 'master_dataset.csv'.")
print("\n--- FINAL DISTRIBUTION ---")
print(master_df.groupby(['dataset', 'split', 'label']).size().unstack(fill_value=0))
master_df.sample(10)

Merge completed! File saved as 'master_dataset.csv'.

--- FINAL DISTRIBUTION ---
label            0     1
dataset split
FEI     test    30   322
        train  140  7322
        val     30   210
FF++    test   150   947
        train  700  4120
        val    150   933

,path,label,split,dataset
14276,/Users/luciapola/Desktop/internship-deepfake-forensic/deepfake-forensics-pipeline/FEI_Split/train/fake/M_45-11_30-11_C16_B30_W30_PA16_PM00_F00_ssd.png,1,train,FEI
5705,/Users/luciapola/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/FaceForensics++_C23/FaceSwap/139_130.mp4,1,train,FF++
999,/Users/luciapola/Desktop/internship-deepfake-forensic/deepfake-forensics-pipeline/FEI_Split/train/fake/M_6-11_112-11_C15_B30_W30_PA15_PM00_F00_ssd.png,1,train,FEI
9162,/Users/luciapola/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/FaceForensics++_C23/DeepFakeDetection/06_26__talking_angry_couch__L5BVR5L9.mp4,1,train,FF++
1379,/Users/luciapola/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/FaceForensics++_C23/original/436.mp4,0,train,FF++
6603,/Users/luciapola/Desktop/internship-deepfake-forensic/deepfake-forensics-pipeline/FEI_Split/train/fake/M_193-11_54-11_C05_B30_W30_PA05_PM00_F00_ssd.png,1,train,FEI
771,/Users/luciapola/Desktop/internship-deepfake-forensic/deepfake-forensics-pipeline/FEI_Split/train/fake/M_116-11_22-11_C08_B30_W30_PA08_PM00_F00_ssd.png,1,train,FEI
14702,/Users/luciapola/Desktop/internship-deepfake-forensic/deepfake-forensics-pipeline/FEI_Split/train/fake/M_46-11_172-11_C15_B50_W50_PA15_PM00_F00_ssd.png,1,train,FEI
14770,/Users/luciapola/Desktop/internship-deepfake-forensic/deepfake-forensics-pipeline/FEI_Split/train/fake/M_150-11_170-11_C01_B30_W30_PA01_PM00_F00_ssd.png,1,train,FEI
7507,/Users/luciapola/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/FaceForensics++_C23/NeuralTextures/610_692.mp4,1,val,FF++